"""Core assistant runtime abstractions."""

from src.core.agent_loop import (
    AgentLoop,
    AgentLoopConfirmRequired,
    AgentLoopConsentRequired,
    AgentLoopStateError,
    AgentLoopToolError,
    AgentRunResult,
    CapabilityAuthorizer,
    CapabilityExecutionContext,
    CapabilityServiceError,
    ConfirmCallbackResult,
    InteractionCancellationReason,
    InteractionCancellationResult,
    PendingInteractionInfo,
    ToolExecutor,
)
from src.core.inbox import InboxEvent, SessionInbox, SessionInboxDispatcher
from src.core.interrupt import (
    InterruptResolution,
    SessionInterrupt,
    SessionInterruptError,
    SessionInterruptExpired,
    SessionInterruptManager,
    SessionInterruptNotFound,
    SessionInterruptResponderMismatch,
)
from src.core.router import (
    COMMANDS_NOT_CONFIGURED_REPLY,
    CardCallback,
    CommandMessageHandler,
    ConfirmCallbackResolver,
    InboundMessageRoute,
    InboundMessageRouteKind,
    InteractionCallbackRouter,
    TextInboundEvent,
    classify_inbound_message,
)
from src.core.session import Actor, BotIdentity, Principal, Session
from src.core.session_manager import GROUP_WELCOME_REPLY, SessionManager, SessionRouteResult

__all__ = [
    "Actor",
    "AgentLoop",
    "AgentLoopConsentRequired",
    "AgentLoopConfirmRequired",
    "AgentLoopStateError",
    "AgentLoopToolError",
    "AgentRunResult",
    "BotIdentity",
    "COMMANDS_NOT_CONFIGURED_REPLY",
    "CapabilityAuthorizer",
    "CapabilityExecutionContext",
    "CapabilityServiceError",
    "ConfirmCallbackResult",
    "CardCallback",
    "CommandMessageHandler",
    "ConfirmCallbackResolver",
    "GROUP_WELCOME_REPLY",
    "InboxEvent",
    "InboundMessageRoute",
    "InboundMessageRouteKind",
    "InteractionCallbackRouter",
    "InteractionCancellationReason",
    "InteractionCancellationResult",
    "InterruptResolution",
    "PendingInteractionInfo",
    "Principal",
    "Session",
    "SessionInbox",
    "SessionInboxDispatcher",
    "SessionInterrupt",
    "SessionInterruptError",
    "SessionInterruptExpired",
    "SessionInterruptManager",
    "SessionInterruptNotFound",
    "SessionInterruptResponderMismatch",
    "SessionManager",
    "TextInboundEvent",
    "SessionRouteResult",
    "ToolExecutor",
    "classify_inbound_message",
]
